mass: 1000.0
altitude_m: 100000.0
length0: 1000.0
controller:
  extend_accel: 0.001      # m/s^2
  retract_accel: 0.001     # m/s^2
  delta_phase_deg: 0.0
  nu_window_deg: 10.0
integrator:
  t_final: 60.0  # 1 minute
  dt_output: 5.0
